version: 1.0.{build}
image: Visual Studio 2017 Preview
skip_tags: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
  - dotnet build -c Release
test_script:
- ps: >-
    dotnet --version
    
    nuget install xunit.runner.console -OutputDirectory packages -Version 2.3.1

    nuget install OpenCover -OutputDirectory packages -Version 4.6.519

    dotnet tool install coveralls.net --version 1.0.0 --tool-path tools

    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" "-targetargs:"".\packages\xunit.runner.console.2.3.1\tools\netcoreapp2.0\xunit.console.dll"" ""SpeldesignBotCore.xUnit.Tests\bin\Release\netcoreapp2.0\SpeldesignBotCore.xUnit.Tests.dll"" -noshadow -appveyor" -filter:"+[SpeldesignBotCore*]* -[SpeldesignBotCore*]*Tests.*" -oldStyle -output:"opencoverCoverage.xml"

    dir

    .\tools\csmacnz.Coveralls.exe --help
    .\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --useRelativePaths --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
